# Generated by Django 3.1.4 on 2020-12-20 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
