# Generated by Django 3.1.4 on 2020-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20201220_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
