# Generated by Django 3.1.4 on 2020-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_student_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
